name: deepreg
channels:
  - defaults
dependencies:
  - cudatoolkit=10.1
  - cudnn=7.6
  - python=3.7
  - pip
  - pip:
      - uninstall tensorflow-gpu tensorflow
      - install tensorflow-gpu==2.10.0
      
